DROP TABLE IF EXISTS armor_stats;

ALTER TABLE armors DROP CONSTRAINT IF EXISTS fk_armor_passive;
ALTER TABLE armors DROP COLUMN IF EXISTS armor_passive_id;
ALTER TABLE armors DROP COLUMN IF EXISTS name;

ALTER TABLE armors ADD COLUMN armor INT NOT NULL DEFAULT 0;
ALTER TABLE armors ADD COLUMN speed INT NOT NULL DEFAULT 0;
ALTER TABLE armors ADD COLUMN stamina INT NOT NULL DEFAULT 0;